blank_issues_enabled: false
contact_links:
  - name: Speedrun.com SFA forum
    url: https://www.speedrun.com/sfa/forums
    about: For general questions and discussion, please use the SFA forum instead of an issue.
